In [7]:
a = 4
m = 3
print(a + m)

7

In [5]:
import pandas as pd

X_train = pd.read_csv("../data/processed/X_train.csv")

print("Number of features:", len(X_train.columns))

for i, column in enumerate(X_train.columns, start=1):
    print(f"{i}. {column}")

Number of features: 78
1. Destination Port
2. Flow Duration
3. Total Fwd Packets
4. Total Backward Packets
5. Total Length of Fwd Packets
6. Total Length of Bwd Packets
7. Fwd Packet Length Max
8. Fwd Packet Length Min
9. Fwd Packet Length Mean
10. Fwd Packet Length Std
11. Bwd Packet Length Max
12. Bwd Packet Length Min
13. Bwd Packet Length Mean
14. Bwd Packet Length Std
15. Flow Bytes/s
16. Flow Packets/s
17. Flow IAT Mean
18. Flow IAT Std
19. Flow IAT Max
20. Flow IAT Min
21. Fwd IAT Total
22. Fwd IAT Mean
23. Fwd IAT Std
24. Fwd IAT Max
25. Fwd IAT Min
26. Bwd IAT Total
27. Bwd IAT Mean
28. Bwd IAT Std
29. Bwd IAT Max
30. Bwd IAT Min
31. Fwd PSH Flags
32. Bwd PSH Flags
33. Fwd URG Flags
34. Bwd URG Flags
35. Fwd Header Length
36. Bwd Header Length
37. Fwd Packets/s
38. Bwd Packets/s
39. Min Packet Length
40. Max Packet Length
41. Packet Length Mean
42. Packet Length Std
43. Packet Length Variance
44. FIN Flag Count
45. SYN Flag Count
46. RST Flag Count
47. PSH Flag Count
48. ACK Flag Count
49. URG Flag Count
50. CWE Flag Count
51. ECE Flag Count
52. Down/Up Ratio
53. Average Packet Size
54. Avg Fwd Segment Size
55. Avg Bwd Segment Size
56. Fwd Header Length.1
57. Fwd Avg Bytes/Bulk
58. Fwd Avg Packets/Bulk
59. Fwd Avg Bulk Rate
60. Bwd Avg Bytes/Bulk
61. Bwd Avg Packets/Bulk
62. Bwd Avg Bulk Rate
63. Subflow Fwd Packets
64. Subflow Fwd Bytes
65. Subflow Bwd Packets
66. Subflow Bwd Bytes
67. Init_Win_bytes_forward
68. Init_Win_bytes_backward
69. act_data_pkt_fwd
70. min_seg_size_forward
71. Active Mean
72. Active Std
73. Active Max
74. Active Min
75. Idle Mean
76. Idle Std
77. Idle Max
78. Idle Min

In [6]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

X_TRAIN_PATH = PROJECT_ROOT / "data" / "processed" / "X_train.csv"

X_train = pd.read_csv(X_TRAIN_PATH)

print("X_train shape:", X_train.shape)
print("Number of features:", len(X_train.columns))

KeyboardInterrupt:

In [8]:
import pandas as pd
import numpy as np
import joblib

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Libraries loaded successfully")

Pandas: 3.0.5
NumPy: 2.5.1
Libraries loaded successfully

In [9]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

X_TRAIN_PATH = PROJECT_ROOT / "data" / "processed" / "X_train.csv"

X_train = pd.read_csv(X_TRAIN_PATH)

print("X_train shape:", X_train.shape)
print("Number of features:", len(X_train.columns))

X_train shape: (2016638, 78)
Number of features: 78

In [10]:
for i, feature in enumerate(X_train.columns, start=1):
    print(f"{i:2}. {feature}")

 1. Destination Port
 2. Flow Duration
 3. Total Fwd Packets
 4. Total Backward Packets
 5. Total Length of Fwd Packets
 6. Total Length of Bwd Packets
 7. Fwd Packet Length Max
 8. Fwd Packet Length Min
 9. Fwd Packet Length Mean
10. Fwd Packet Length Std
11. Bwd Packet Length Max
12. Bwd Packet Length Min
13. Bwd Packet Length Mean
14. Bwd Packet Length Std
15. Flow Bytes/s
16. Flow Packets/s
17. Flow IAT Mean
18. Flow IAT Std
19. Flow IAT Max
20. Flow IAT Min
21. Fwd IAT Total
22. Fwd IAT Mean
23. Fwd IAT Std
24. Fwd IAT Max
25. Fwd IAT Min
26. Bwd IAT Total
27. Bwd IAT Mean
28. Bwd IAT Std
29. Bwd IAT Max
30. Bwd IAT Min
31. Fwd PSH Flags
32. Bwd PSH Flags
33. Fwd URG Flags
34. Bwd URG Flags
35. Fwd Header Length
36. Bwd Header Length
37. Fwd Packets/s
38. Bwd Packets/s
39. Min Packet Length
40. Max Packet Length
41. Packet Length Mean
42. Packet Length Std
43. Packet Length Variance
44. FIN Flag Count
45. SYN Flag Count
46. RST Flag Count
47. PSH Flag Count
48. ACK Flag Count
49. URG Flag Count
50. CWE Flag Count
51. ECE Flag Count
52. Down/Up Ratio
53. Average Packet Size
54. Avg Fwd Segment Size
55. Avg Bwd Segment Size
56. Fwd Header Length.1
57. Fwd Avg Bytes/Bulk
58. Fwd Avg Packets/Bulk
59. Fwd Avg Bulk Rate
60. Bwd Avg Bytes/Bulk
61. Bwd Avg Packets/Bulk
62. Bwd Avg Bulk Rate
63. Subflow Fwd Packets
64. Subflow Fwd Bytes
65. Subflow Bwd Packets
66. Subflow Bwd Bytes
67. Init_Win_bytes_forward
68. Init_Win_bytes_backward
69. act_data_pkt_fwd
70. min_seg_size_forward
71. Active Mean
72. Active Std
73. Active Max
74. Active Min
75. Idle Mean
76. Idle Std
77. Idle Max
78. Idle Min

In [11]:
features = list(X_train.columns)

print("Total features:", len(features))

for start in range(0, len(features), 20):
    print(f"\n--- Features {start + 1} to {min(start + 20, len(features))} ---")
    for i, feature in enumerate(features[start:start + 20], start=start + 1):
        print(f"{i:2}. {feature}")

Total features: 78

--- Features 1 to 20 ---
 1. Destination Port
 2. Flow Duration
 3. Total Fwd Packets
 4. Total Backward Packets
 5. Total Length of Fwd Packets
 6. Total Length of Bwd Packets
 7. Fwd Packet Length Max
 8. Fwd Packet Length Min
 9. Fwd Packet Length Mean
10. Fwd Packet Length Std
11. Bwd Packet Length Max
12. Bwd Packet Length Min
13. Bwd Packet Length Mean
14. Bwd Packet Length Std
15. Flow Bytes/s
16. Flow Packets/s
17. Flow IAT Mean
18. Flow IAT Std
19. Flow IAT Max
20. Flow IAT Min

--- Features 21 to 40 ---
21. Fwd IAT Total
22. Fwd IAT Mean
23. Fwd IAT Std
24. Fwd IAT Max
25. Fwd IAT Min
26. Bwd IAT Total
27. Bwd IAT Mean
28. Bwd IAT Std
29. Bwd IAT Max
30. Bwd IAT Min
31. Fwd PSH Flags
32. Bwd PSH Flags
33. Fwd URG Flags
34. Bwd URG Flags
35. Fwd Header Length
36. Bwd Header Length
37. Fwd Packets/s
38. Bwd Packets/s
39. Min Packet Length
40. Max Packet Length

--- Features 41 to 60 ---
41. Packet Length Mean
42. Packet Length Std
43. Packet Length Variance
44. FIN Flag Count
45. SYN Flag Count
46. RST Flag Count
47. PSH Flag Count
48. ACK Flag Count
49. URG Flag Count
50. CWE Flag Count
51. ECE Flag Count
52. Down/Up Ratio
53. Average Packet Size
54. Avg Fwd Segment Size
55. Avg Bwd Segment Size
56. Fwd Header Length.1
57. Fwd Avg Bytes/Bulk
58. Fwd Avg Packets/Bulk
59. Fwd Avg Bulk Rate
60. Bwd Avg Bytes/Bulk

--- Features 61 to 78 ---
61. Bwd Avg Packets/Bulk
62. Bwd Avg Bulk Rate
63. Subflow Fwd Packets
64. Subflow Fwd Bytes
65. Subflow Bwd Packets
66. Subflow Bwd Bytes
67. Init_Win_bytes_forward
68. Init_Win_bytes_backward
69. act_data_pkt_fwd
70. min_seg_size_forward
71. Active Mean
72. Active Std
73. Active Max
74. Active Min
75. Idle Mean
76. Idle Std
77. Idle Max
78. Idle Min

In [15]:
feature_stats = X_train.describe().T

display(
    feature_stats[
        ["mean", "std", "min", "max"]
    ]
)

                                     mean  std          min         max
Destination Port            -3.574139e-17  1.0    -0.456927    2.990990
Flow Duration                1.601034e-17  1.0    -0.471065    2.934654
Total Fwd Packets            3.636151e-17  1.0    -0.011627  266.800619
Total Backward Packets       3.619239e-17  1.0    -0.010903  265.898486
Total Length of Fwd Packets  3.441660e-17  1.0    -0.093887  360.067934
Total Length of Bwd Packets  5.558520e-17  1.0    -0.007658  263.501454
Fwd Packet Length Max        1.178226e-17  1.0    -0.306145   32.574120
Fwd Packet Length Min        9.893714e-18  1.0    -0.315578   37.863642
Fwd Packet Length Mean       3.943392e-17  1.0    -0.325231   30.133078
Fwd Packet Length Std        3.475484e-17  1.0    -0.260715   23.784743
Bwd Packet Length Max        2.689061e-17  1.0    -0.478360    9.101068
Bwd Packet Length Min       -7.328677e-17  1.0    -0.608761   29.652350
Bwd Packet Length Mean      -1.870222e-17  1.0    -0.538597    6.371281
Bwd Packet Length Std       -3.436022e-17  1.0    -0.427394    7.193368
Flow Bytes/s                 5.155443e-17  1.0    -9.971232   78.645753
Flow Packets/s               9.019910e-18  1.0   -10.100922   19.502190
Flow IAT Mean                3.557227e-17  1.0    -0.308405   25.244560
Flow IAT Std                -2.032299e-17  1.0    -0.387683    9.640496
Flow IAT Max                 4.639616e-17  1.0    -0.401079    4.271260
Flow IAT Min                 4.617067e-17  1.0    -0.056760   39.465497
Fwd IAT Total                3.653064e-17  1.0    -0.462266    2.949897
Fwd IAT Mean                -1.281109e-17  1.0    -0.291429   11.677700
Fwd IAT Std                 -7.215928e-18  1.0    -0.361724    7.982750
Fwd IAT Max                  1.127489e-18  1.0    -0.393717    4.263934
Fwd IAT Min                  3.381057e-17  1.0    -0.125520   13.102603
Bwd IAT Total               -3.799637e-17  1.0    -0.367576    3.601925
Bwd IAT Mean                 8.850787e-18  1.0    -0.215822   12.546217
Bwd IAT Std                 -3.227437e-18  1.0    -0.251512   12.334553
Bwd IAT Max                  1.409361e-19  1.0    -0.290580    6.341789
Bwd IAT Min                  2.498797e-17  1.0    -0.123571   13.500480
Fwd PSH Flags               -4.276001e-17  1.0    -0.226002    4.424744
Bwd PSH Flags                0.000000e+00  0.0     0.000000    0.000000
Fwd URG Flags                7.745848e-17  1.0    -0.005807  172.207553
Bwd URG Flags                0.000000e+00  0.0     0.000000    0.000000
Fwd Header Length           -4.803102e-17  1.0 -1045.844864    0.501398
Bwd Header Length           -5.034237e-17  1.0  -798.147276    4.341479
Fwd Packets/s                2.876506e-17  1.0    -0.211345   15.312096
Bwd Packets/s                1.014740e-17  1.0    -0.170761   52.226392
Min Packet Length           -2.153504e-17  1.0    -0.655214   55.680565
Max Packet Length            2.347995e-17  1.0    -0.501395   11.197274
Packet Length Mean           2.646780e-17  1.0    -0.599037    8.577295
Packet Length Std            4.927126e-17  1.0    -0.499639    6.660397
Packet Length Variance       2.012568e-17  1.0    -0.314193   12.583524
FIN Flag Count              -6.497154e-18  1.0    -0.182065    5.492549
SYN Flag Count              -4.276001e-17  1.0    -0.226002    4.424744
RST Flag Count               8.399792e-17  1.0    -0.016637   60.108623
PSH Flag Count              -5.682544e-17  1.0    -0.651161    1.535719
ACK Flag Count              -6.629634e-17  1.0    -0.673035    1.485807
URG Flag Count              -3.495215e-17  1.0    -0.335870    2.977338
CWE Flag Count               7.745848e-17  1.0    -0.005807  172.207553
ECE Flag Count              -8.738038e-19  1.0    -0.016681   59.947645
Down/Up Ratio               -2.824359e-17  1.0    -1.002133  222.292698
Average Packet Size          3.796819e-17  1.0    -0.615029   10.052834
Avg Fwd Segment Size         3.943392e-17  1.0    -0.325231   30.133078
Avg Bwd Segment Size         8.568915e-17  1.0    -0.538597    6.371281
Fwd Header Length.1         -4.803102e-17  1.0 -1045.844864    0.501398
Fwd Avg Bytes/Bulk           0.000000e+00  0.0     0.000000    0.000000
Fwd Avg Packets/Bulk         0.000000e+00  0.0     0.000000    0.000000
Fwd Avg Bulk Rate            0.000000e+00  0.0     0.000000    0.000000
Bwd Avg Bytes/Bulk           0.000000e+00  0.0     0.000000    0.000000
Bwd Avg Packets/Bulk         0.000000e+00  0.0     0.000000    0.000000
Bwd Avg Bulk Rate            0.000000e+00  0.0     0.000000    0.000000
Subflow Fwd Packets          3.636151e-17  1.0    -0.011627  266.800619
Subflow Fwd Bytes            3.441660e-17  1.0    -0.093887  360.067934
Subflow Bwd Packets          3.619239e-17  1.0    -0.010903  265.898486
Subflow Bwd Bytes            3.850374e-17  1.0    -0.007658  263.499230
Init_Win_bytes_forward       1.713783e-17  1.0    -0.497989    3.986468
Init_Win_bytes_backward      4.769278e-17  1.0    -0.249889    7.087951
act_data_pkt_fwd             3.145694e-17  1.0    -0.008864  307.640236
min_seg_size_forward        -3.421929e-17  1.0  -519.794328    0.002678
Active Mean                  6.466148e-17  1.0    -0.135369  162.242697
Active Std                   3.901111e-17  1.0    -0.110854  168.873226
Active Max                   7.430151e-17  1.0    -0.159110  101.392953
Active Min                   7.249753e-17  1.0    -0.109241  183.203869
Idle Mean                    5.293560e-17  1.0    -0.375838    4.453786
Idle Std                     9.256683e-17  1.0    -0.115877   15.679169
Idle Max                    -3.100594e-17  1.0    -0.381176    4.303834
Idle Min                    -1.085208e-17  1.0    -0.361859    4.519988

In [16]:
pd.set_option("display.max_rows", 100)

display(
    feature_stats[["mean", "std", "min", "max"]]
)

                                     mean  std          min         max
Destination Port            -3.574139e-17  1.0    -0.456927    2.990990
Flow Duration                1.601034e-17  1.0    -0.471065    2.934654
Total Fwd Packets            3.636151e-17  1.0    -0.011627  266.800619
Total Backward Packets       3.619239e-17  1.0    -0.010903  265.898486
Total Length of Fwd Packets  3.441660e-17  1.0    -0.093887  360.067934
Total Length of Bwd Packets  5.558520e-17  1.0    -0.007658  263.501454
Fwd Packet Length Max        1.178226e-17  1.0    -0.306145   32.574120
Fwd Packet Length Min        9.893714e-18  1.0    -0.315578   37.863642
Fwd Packet Length Mean       3.943392e-17  1.0    -0.325231   30.133078
Fwd Packet Length Std        3.475484e-17  1.0    -0.260715   23.784743
Bwd Packet Length Max        2.689061e-17  1.0    -0.478360    9.101068
Bwd Packet Length Min       -7.328677e-17  1.0    -0.608761   29.652350
Bwd Packet Length Mean      -1.870222e-17  1.0    -0.538597    6.371281
Bwd Packet Length Std       -3.436022e-17  1.0    -0.427394    7.193368
Flow Bytes/s                 5.155443e-17  1.0    -9.971232   78.645753
Flow Packets/s               9.019910e-18  1.0   -10.100922   19.502190
Flow IAT Mean                3.557227e-17  1.0    -0.308405   25.244560
Flow IAT Std                -2.032299e-17  1.0    -0.387683    9.640496
Flow IAT Max                 4.639616e-17  1.0    -0.401079    4.271260
Flow IAT Min                 4.617067e-17  1.0    -0.056760   39.465497
Fwd IAT Total                3.653064e-17  1.0    -0.462266    2.949897
Fwd IAT Mean                -1.281109e-17  1.0    -0.291429   11.677700
Fwd IAT Std                 -7.215928e-18  1.0    -0.361724    7.982750
Fwd IAT Max                  1.127489e-18  1.0    -0.393717    4.263934
Fwd IAT Min                  3.381057e-17  1.0    -0.125520   13.102603
Bwd IAT Total               -3.799637e-17  1.0    -0.367576    3.601925
Bwd IAT Mean                 8.850787e-18  1.0    -0.215822   12.546217
Bwd IAT Std                 -3.227437e-18  1.0    -0.251512   12.334553
Bwd IAT Max                  1.409361e-19  1.0    -0.290580    6.341789
Bwd IAT Min                  2.498797e-17  1.0    -0.123571   13.500480
Fwd PSH Flags               -4.276001e-17  1.0    -0.226002    4.424744
Bwd PSH Flags                0.000000e+00  0.0     0.000000    0.000000
Fwd URG Flags                7.745848e-17  1.0    -0.005807  172.207553
Bwd URG Flags                0.000000e+00  0.0     0.000000    0.000000
Fwd Header Length           -4.803102e-17  1.0 -1045.844864    0.501398
Bwd Header Length           -5.034237e-17  1.0  -798.147276    4.341479
Fwd Packets/s                2.876506e-17  1.0    -0.211345   15.312096
Bwd Packets/s                1.014740e-17  1.0    -0.170761   52.226392
Min Packet Length           -2.153504e-17  1.0    -0.655214   55.680565
Max Packet Length            2.347995e-17  1.0    -0.501395   11.197274
Packet Length Mean           2.646780e-17  1.0    -0.599037    8.577295
Packet Length Std            4.927126e-17  1.0    -0.499639    6.660397
Packet Length Variance       2.012568e-17  1.0    -0.314193   12.583524
FIN Flag Count              -6.497154e-18  1.0    -0.182065    5.492549
SYN Flag Count              -4.276001e-17  1.0    -0.226002    4.424744
RST Flag Count               8.399792e-17  1.0    -0.016637   60.108623
PSH Flag Count              -5.682544e-17  1.0    -0.651161    1.535719
ACK Flag Count              -6.629634e-17  1.0    -0.673035    1.485807
URG Flag Count              -3.495215e-17  1.0    -0.335870    2.977338
CWE Flag Count               7.745848e-17  1.0    -0.005807  172.207553
ECE Flag Count              -8.738038e-19  1.0    -0.016681   59.947645
Down/Up Ratio               -2.824359e-17  1.0    -1.002133  222.292698
Average Packet Size          3.796819e-17  1.0    -0.615029   10.052834
Avg Fwd Segment Size         3.943392e-17  1.0    -0.325231   30.133078
Avg Bwd Segment Size         8.568915e-17  1.0    -0.538597    6.371281
Fwd Header Length.1         -4.803102e-17  1.0 -1045.844864    0.501398
Fwd Avg Bytes/Bulk           0.000000e+00  0.0     0.000000    0.000000
Fwd Avg Packets/Bulk         0.000000e+00  0.0     0.000000    0.000000
Fwd Avg Bulk Rate            0.000000e+00  0.0     0.000000    0.000000
Bwd Avg Bytes/Bulk           0.000000e+00  0.0     0.000000    0.000000
Bwd Avg Packets/Bulk         0.000000e+00  0.0     0.000000    0.000000
Bwd Avg Bulk Rate            0.000000e+00  0.0     0.000000    0.000000
Subflow Fwd Packets          3.636151e-17  1.0    -0.011627  266.800619
Subflow Fwd Bytes            3.441660e-17  1.0    -0.093887  360.067934
Subflow Bwd Packets          3.619239e-17  1.0    -0.010903  265.898486
Subflow Bwd Bytes            3.850374e-17  1.0    -0.007658  263.499230
Init_Win_bytes_forward       1.713783e-17  1.0    -0.497989    3.986468
Init_Win_bytes_backward      4.769278e-17  1.0    -0.249889    7.087951
act_data_pkt_fwd             3.145694e-17  1.0    -0.008864  307.640236
min_seg_size_forward        -3.421929e-17  1.0  -519.794328    0.002678
Active Mean                  6.466148e-17  1.0    -0.135369  162.242697
Active Std                   3.901111e-17  1.0    -0.110854  168.873226
Active Max                   7.430151e-17  1.0    -0.159110  101.392953
Active Min                   7.249753e-17  1.0    -0.109241  183.203869
Idle Mean                    5.293560e-17  1.0    -0.375838    4.453786
Idle Std                     9.256683e-17  1.0    -0.115877   15.679169
Idle Max                    -3.100594e-17  1.0    -0.381176    4.303834
Idle Min                    -1.085208e-17  1.0    -0.361859    4.519988

In [17]:
print(X_train.dtypes.value_counts())

float64    78
Name: count, dtype: int64

In [21]:
import sys
print(sys.executable)

c:\Users\GODLOVE BARNES\Desktop\Project\Web\web-app-intrusion-detection\venv\Scripts\python.exe

In [22]:
import pandas as pd
print(pd.__version__)

3.0.5

In [24]:
import sys
import subprocess

subprocess.check_call([
    sys.executable,
    "-m",
    "pip",
    "install",
    "scapy"
])

0

In [25]:
from scapy.all import IP, TCP

print("Scapy imported successfully")
print("IP layer:", IP)
print("TCP layer:", TCP)

Scapy imported successfully
IP layer: <class 'scapy.layers.inet.IP'>
TCP layer: <class 'scapy.layers.inet.TCP'>

In [26]:
from scapy.all import IP, TCP, Raw
import time

# Create a small simulated TCP flow
packets = []

p1 = IP(src="127.0.0.1", dst="127.0.0.1") / TCP(
    sport=50000,
    dport=8000,
    flags="S"
)

p2 = IP(src="127.0.0.1", dst="127.0.0.1") / TCP(
    sport=8000,
    dport=50000,
    flags="SA"
)

p3 = IP(src="127.0.0.1", dst="127.0.0.1") / TCP(
    sport=50000,
    dport=8000,
    flags="PA"
) / Raw(load=b"GET / HTTP/1.1\r\n")

packets.extend([p1, p2, p3])

print("Packets in test flow:", len(packets))

for packet in packets:
    print(packet.summary())

Packets in test flow: 3
IP / TCP 127.0.0.1:50000 > 127.0.0.1:8000 S
IP / TCP 127.0.0.1:8000 > 127.0.0.1:50000 SA
IP / TCP 127.0.0.1:50000 > 127.0.0.1:8000 PA / Raw

In [27]:
# Define the flow direction
src_ip = "127.0.0.1"
src_port = 50000

dst_ip = "127.0.0.1"
dst_port = 8000

forward_packets = []
backward_packets = []

for packet in packets:
    if not packet.haslayer(IP) or not packet.haslayer(TCP):
        continue

    ip = packet[IP]
    tcp = packet[TCP]

    if ip.src == src_ip and tcp.sport == src_port:
        forward_packets.append(packet)

    elif ip.src == dst_ip and tcp.sport == dst_port:
        backward_packets.append(packet)

print("Forward packets:", len(forward_packets))
print("Backward packets:", len(backward_packets))

Forward packets: 2
Backward packets: 1

In [28]:
fwd_lengths = [
    len(packet[TCP].payload)
    for packet in forward_packets
]

bwd_lengths = [
    len(packet[TCP].payload)
    for packet in backward_packets
]

print("Forward packet lengths:", fwd_lengths)
print("Backward packet lengths:", bwd_lengths)

Forward packet lengths: [0, 16]
Backward packet lengths: [0]

In [29]:
fwd_lengths = [len(packet) for packet in forward_packets]
bwd_lengths = [len(packet) for packet in backward_packets]

print("Forward packet lengths:", fwd_lengths)
print("Backward packet lengths:", bwd_lengths)

Forward packet lengths: [40, 56]
Backward packet lengths: [40]

In [30]:
import numpy as np

features_basic = {
    "Destination Port": dst_port,
    "Total Fwd Packets": len(forward_packets),
    "Total Backward Packets": len(backward_packets),

    "Fwd Packet Length Max": max(fwd_lengths) if fwd_lengths else 0,
    "Fwd Packet Length Min": min(fwd_lengths) if fwd_lengths else 0,
    "Fwd Packet Length Mean": np.mean(fwd_lengths) if fwd_lengths else 0,
    "Fwd Packet Length Std": np.std(fwd_lengths) if len(fwd_lengths) > 1 else 0,

    "Bwd Packet Length Max": max(bwd_lengths) if bwd_lengths else 0,
    "Bwd Packet Length Min": min(bwd_lengths) if bwd_lengths else 0,
    "Bwd Packet Length Mean": np.mean(bwd_lengths) if bwd_lengths else 0,
    "Bwd Packet Length Std": np.std(bwd_lengths) if len(bwd_lengths) > 1 else 0,
}

for name, value in features_basic.items():
    print(f"{name}: {value}")

Destination Port: 8000
Total Fwd Packets: 2
Total Backward Packets: 1
Fwd Packet Length Max: 56
Fwd Packet Length Min: 40
Fwd Packet Length Mean: 48.0
Fwd Packet Length Std: 8.0
Bwd Packet Length Max: 40
Bwd Packet Length Min: 40
Bwd Packet Length Mean: 40.0
Bwd Packet Length Std: 0

In [31]:
import numpy as np

# Get timestamps for all packets in the flow
timestamps = [float(packet.time) for packet in packets]

# Flow duration in microseconds
flow_duration = (
    (max(timestamps) - min(timestamps)) * 1_000_000
    if len(timestamps) > 1
    else 0
)

# Inter-arrival times in microseconds
iat = np.diff(timestamps) * 1_000_000 if len(timestamps) > 1 else np.array([])

print("Flow Duration:", flow_duration)
print("Packet IATs:", iat)

Flow Duration: 1325.6072998046875
Packet IATs: [819.68307495 505.92422485]

In [32]:
flow_iat_mean = np.mean(iat) if len(iat) > 0 else 0
flow_iat_std = np.std(iat) if len(iat) > 1 else 0
flow_iat_max = np.max(iat) if len(iat) > 0 else 0
flow_iat_min = np.min(iat) if len(iat) > 0 else 0

print("Flow IAT Mean:", flow_iat_mean)
print("Flow IAT Std:", flow_iat_std)
print("Flow IAT Max:", flow_iat_max)
print("Flow IAT Min:", flow_iat_min)

Flow IAT Mean: 662.8036499023438
Flow IAT Std: 156.87942504882812
Flow IAT Max: 819.6830749511719
Flow IAT Min: 505.9242248535156

In [34]:
# Number of forward and backward packets
total_fwd_packets = len(forward_packets)
total_bwd_packets = len(backward_packets)

# Total packets
total_packets = len(packets)

# Flow duration in seconds
flow_duration_seconds = flow_duration / 1_000_000

# Flow packet rate
flow_packets_per_sec = (
    total_packets / flow_duration_seconds
    if flow_duration_seconds > 0
    else 0
)

# Forward packet rate
fwd_packets_per_sec = (
    total_fwd_packets / flow_duration_seconds
    if flow_duration_seconds > 0
    else 0
)

# Backward packet rate
bwd_packets_per_sec = (
    total_bwd_packets / flow_duration_seconds
    if flow_duration_seconds > 0
    else 0
)

print("Total Packets:", total_packets)
print("Forward Packets:", total_fwd_packets)
print("Backward Packets:", total_bwd_packets)
print("Flow Packets/s:", flow_packets_per_sec)
print("Fwd Packets/s:", fwd_packets_per_sec)
print("Bwd Packets/s:", bwd_packets_per_sec)

Total Packets: 3
Forward Packets: 2
Backward Packets: 1
Flow Packets/s: 2263.113669064748
Fwd Packets/s: 1508.7424460431655
Bwd Packets/s: 754.3712230215828

In [35]:
# Calculate total bytes in the flow
total_bytes = sum(len(packet) for packet in packets)

# Flow bytes per second
flow_bytes_per_sec = (
    total_bytes / flow_duration_seconds
    if flow_duration_seconds > 0
    else 0
)

print("Total Bytes:", total_bytes)
print("Flow Bytes/s:", flow_bytes_per_sec)

Total Bytes: 136
Flow Bytes/s: 102594.48633093525

In [36]:
# Calculate total bytes in forward and backward directions
total_length_fwd = sum(len(packet) for packet in forward_packets)
total_length_bwd = sum(len(packet) for packet in backward_packets)

print("Total Length of Fwd Packets:", total_length_fwd)
print("Total Length of Bwd Packets:", total_length_bwd)

Total Length of Fwd Packets: 96
Total Length of Bwd Packets: 40

In [37]:
import numpy as np

packet_lengths = np.array([len(packet) for packet in packets], dtype=float)

min_packet_length = np.min(packet_lengths)
max_packet_length = np.max(packet_lengths)
packet_length_mean = np.mean(packet_lengths)
packet_length_std = np.std(packet_lengths)
packet_length_variance = np.var(packet_lengths)

print("Min Packet Length:", min_packet_length)
print("Max Packet Length:", max_packet_length)
print("Packet Length Mean:", packet_length_mean)
print("Packet Length Std:", packet_length_std)
print("Packet Length Variance:", packet_length_variance)

Min Packet Length: 40.0
Max Packet Length: 56.0
Packet Length Mean: 45.333333333333336
Packet Length Std: 7.542472332656507
Packet Length Variance: 56.88888888888889

In [38]:
# TCP flag counts

fin_flag_count = 0
syn_flag_count = 0
rst_flag_count = 0
psh_flag_count = 0
ack_flag_count = 0
urg_flag_count = 0
cwe_flag_count = 0
ece_flag_count = 0

for packet in packets:
    if packet.haslayer(TCP):
        flags = packet[TCP].flags

        if "F" in flags:
            fin_flag_count += 1
        if "S" in flags:
            syn_flag_count += 1
        if "R" in flags:
            rst_flag_count += 1
        if "P" in flags:
            psh_flag_count += 1
        if "A" in flags:
            ack_flag_count += 1
        if "U" in flags:
            urg_flag_count += 1
        if "C" in flags:
            cwe_flag_count += 1
        if "E" in flags:
            ece_flag_count += 1

print("FIN Flag Count:", fin_flag_count)
print("SYN Flag Count:", syn_flag_count)
print("RST Flag Count:", rst_flag_count)
print("PSH Flag Count:", psh_flag_count)
print("ACK Flag Count:", ack_flag_count)
print("URG Flag Count:", urg_flag_count)
print("CWE Flag Count:", cwe_flag_count)
print("ECE Flag Count:", ece_flag_count)

FIN Flag Count: 0
SYN Flag Count: 2
RST Flag Count: 0
PSH Flag Count: 1
ACK Flag Count: 2
URG Flag Count: 0
CWE Flag Count: 0
ECE Flag Count: 0

In [39]:
# Down/Up Ratio
down_up_ratio = (
    len(backward_packets) / len(forward_packets)
    if len(forward_packets) > 0
    else 0
)

# Average Packet Size
average_packet_size = (
    np.mean(packet_lengths)
    if len(packet_lengths) > 0
    else 0
)

# Average Forward Segment Size
avg_fwd_segment_size = (
    total_length_fwd / len(forward_packets)
    if len(forward_packets) > 0
    else 0
)

# Average Backward Segment Size
avg_bwd_segment_size = (
    total_length_bwd / len(backward_packets)
    if len(backward_packets) > 0
    else 0
)

print("Down/Up Ratio:", down_up_ratio)
print("Average Packet Size:", average_packet_size)
print("Avg Fwd Segment Size:", avg_fwd_segment_size)
print("Avg Bwd Segment Size:", avg_bwd_segment_size)

Down/Up Ratio: 0.5
Average Packet Size: 45.333333333333336
Avg Fwd Segment Size: 48.0
Avg Bwd Segment Size: 40.0

In [40]:
# Bulk transfer features
# No bulk transfer activity in the current test flow

fwd_avg_bytes_bulk = 0
fwd_avg_packets_bulk = 0
fwd_avg_bulk_rate = 0

bwd_avg_bytes_bulk = 0
bwd_avg_packets_bulk = 0
bwd_avg_bulk_rate = 0

print("Fwd Avg Bytes/Bulk:", fwd_avg_bytes_bulk)
print("Fwd Avg Packets/Bulk:", fwd_avg_packets_bulk)
print("Fwd Avg Bulk Rate:", fwd_avg_bulk_rate)
print("Bwd Avg Bytes/Bulk:", bwd_avg_bytes_bulk)
print("Bwd Avg Packets/Bulk:", bwd_avg_packets_bulk)
print("Bwd Avg Bulk Rate:", bwd_avg_bulk_rate)

Fwd Avg Bytes/Bulk: 0
Fwd Avg Packets/Bulk: 0
Fwd Avg Bulk Rate: 0
Bwd Avg Bytes/Bulk: 0
Bwd Avg Packets/Bulk: 0
Bwd Avg Bulk Rate: 0

In [41]:
# Subflow features

subflow_fwd_packets = len(forward_packets)
subflow_fwd_bytes = total_length_fwd

subflow_bwd_packets = len(backward_packets)
subflow_bwd_bytes = total_length_bwd

print("Subflow Fwd Packets:", subflow_fwd_packets)
print("Subflow Fwd Bytes:", subflow_fwd_bytes)
print("Subflow Bwd Packets:", subflow_bwd_packets)
print("Subflow Bwd Bytes:", subflow_bwd_bytes)

Subflow Fwd Packets: 2
Subflow Fwd Bytes: 96
Subflow Bwd Packets: 1
Subflow Bwd Bytes: 40

In [42]:
# Initial TCP window sizes

init_win_bytes_forward = 0
init_win_bytes_backward = 0

for packet in packets:
    if packet.haslayer(TCP):
        tcp = packet[TCP]
        flags = tcp.flags

        # Forward SYN (SYN set, ACK not set)
        if "S" in flags and "A" not in flags:
            init_win_bytes_forward = tcp.window

        # Backward SYN-ACK
        elif "S" in flags and "A" in flags:
            init_win_bytes_backward = tcp.window

print("Init_Win_bytes_forward:", init_win_bytes_forward)
print("Init_Win_bytes_backward:", init_win_bytes_backward)

Init_Win_bytes_forward: 8192
Init_Win_bytes_backward: 8192

In [43]:
# TCP activity features

# Number of forward packets carrying actual TCP payload data
act_data_pkt_fwd = 0

# Minimum forward TCP segment size
forward_segment_sizes = []

for packet in forward_packets:
    if packet.haslayer(TCP):
        tcp = packet[TCP]

        # TCP payload
        if tcp.payload:
            act_data_pkt_fwd += 1

        # TCP segment size
        forward_segment_sizes.append(len(packet))

min_seg_size_forward = (
    min(forward_segment_sizes)
    if forward_segment_sizes
    else 0
)

print("act_data_pkt_fwd:", act_data_pkt_fwd)
print("min_seg_size_forward:", min_seg_size_forward)

act_data_pkt_fwd: 1
min_seg_size_forward: 40

In [44]:
# Active and Idle time features

timestamps = sorted(
    [float(packet.time) for packet in packets]
)

active_times = []
idle_times = []

# Time gaps between consecutive packets
for i in range(1, len(timestamps)):
    gap = (timestamps[i] - timestamps[i - 1]) * 1_000_000  # microseconds

    # For this initial test flow, treat gaps <= 1 second as active
    # and larger gaps as idle.
    if gap <= 1_000_000:
        active_times.append(gap)
    else:
        idle_times.append(gap)

# Active statistics
if active_times:
    active_mean = np.mean(active_times)
    active_std = np.std(active_times)
    active_max = np.max(active_times)
    active_min = np.min(active_times)
else:
    active_mean = 0
    active_std = 0
    active_max = 0
    active_min = 0

# Idle statistics
if idle_times:
    idle_mean = np.mean(idle_times)
    idle_std = np.std(idle_times)
    idle_max = np.max(idle_times)
    idle_min = np.min(idle_times)
else:
    idle_mean = 0
    idle_std = 0
    idle_max = 0
    idle_min = 0

print("Active Mean:", active_mean)
print("Active Std:", active_std)
print("Active Max:", active_max)
print("Active Min:", active_min)

print("Idle Mean:", idle_mean)
print("Idle Std:", idle_std)
print("Idle Max:", idle_max)
print("Idle Min:", idle_min)

Active Mean: 662.8036499023438
Active Std: 156.87942504882812
Active Max: 819.6830749511719
Active Min: 505.9242248535156
Idle Mean: 0
Idle Std: 0
Idle Max: 0
Idle Min: 0

In [47]:
# Recalculate the packet-length variables from the captured flow

fwd_lengths = [
    len(packet)
    for packet in forward_packets
    if packet.haslayer(TCP)
]

bwd_lengths = [
    len(packet)
    for packet in backward_packets
    if packet.haslayer(TCP)
]

# Forward packet length statistics
fwd_packet_length_max = max(fwd_lengths) if fwd_lengths else 0
fwd_packet_length_min = min(fwd_lengths) if fwd_lengths else 0
fwd_packet_length_mean = np.mean(fwd_lengths) if fwd_lengths else 0
fwd_packet_length_std = np.std(fwd_lengths) if len(fwd_lengths) > 1 else 0

# Backward packet length statistics
bwd_packet_length_max = max(bwd_lengths) if bwd_lengths else 0
bwd_packet_length_min = min(bwd_lengths) if bwd_lengths else 0
bwd_packet_length_mean = np.mean(bwd_lengths) if bwd_lengths else 0
bwd_packet_length_std = np.std(bwd_lengths) if len(bwd_lengths) > 1 else 0

print("Forward packet lengths:", fwd_lengths)
print("Backward packet lengths:", bwd_lengths)

print("\nFwd Packet Length Max:", fwd_packet_length_max)
print("Fwd Packet Length Min:", fwd_packet_length_min)
print("Fwd Packet Length Mean:", fwd_packet_length_mean)
print("Fwd Packet Length Std:", fwd_packet_length_std)

print("\nBwd Packet Length Max:", bwd_packet_length_max)
print("Bwd Packet Length Min:", bwd_packet_length_min)
print("Bwd Packet Length Mean:", bwd_packet_length_mean)
print("Bwd Packet Length Std:", bwd_packet_length_std)

Forward packet lengths: [40, 56]
Backward packet lengths: [40]

Fwd Packet Length Max: 56
Fwd Packet Length Min: 40
Fwd Packet Length Mean: 48.0
Fwd Packet Length Std: 8.0

Bwd Packet Length Max: 40
Bwd Packet Length Min: 40
Bwd Packet Length Mean: 40.0
Bwd Packet Length Std: 0

In [48]:
import pandas as pd
import numpy as np

# Load the training feature names
X_train = pd.read_csv("../data/processed/X_train.csv", nrows=1)

training_features = X_train.columns.tolist()

print("Training features:", len(training_features))


# Build the live feature vector
live_features = {
    "Destination Port": dst_port,
    "Flow Duration": flow_duration,
    "Total Fwd Packets": len(forward_packets),
    "Total Backward Packets": len(backward_packets),
    "Total Length of Fwd Packets": total_length_fwd,
    "Total Length of Bwd Packets": total_length_bwd,

    "Fwd Packet Length Max": fwd_packet_length_max,
    "Fwd Packet Length Min": fwd_packet_length_min,
    "Fwd Packet Length Mean": fwd_packet_length_mean,
    "Fwd Packet Length Std": fwd_packet_length_std,

    "Bwd Packet Length Max": bwd_packet_length_max,
    "Bwd Packet Length Min": bwd_packet_length_min,
    "Bwd Packet Length Mean": bwd_packet_length_mean,
    "Bwd Packet Length Std": bwd_packet_length_std,

    "Flow Bytes/s": flow_bytes_per_sec,
    "Flow Packets/s": flow_packets_per_sec,

    "Flow IAT Mean": flow_iat_mean,
    "Flow IAT Std": flow_iat_std,
    "Flow IAT Max": flow_iat_max,
    "Flow IAT Min": flow_iat_min,

    "Fwd IAT Total": fwd_iat_total,
    "Fwd IAT Mean": fwd_iat_mean,
    "Fwd IAT Std": fwd_iat_std,
    "Fwd IAT Max": fwd_iat_max,
    "Fwd IAT Min": fwd_iat_min,

    "Bwd IAT Total": bwd_iat_total,
    "Bwd IAT Mean": bwd_iat_mean,
    "Bwd IAT Std": bwd_iat_std,
    "Bwd IAT Max": bwd_iat_max,
    "Bwd IAT Min": bwd_iat_min,

    "Fwd PSH Flags": fwd_psh_flags,
    "Bwd PSH Flags": bwd_psh_flags,
    "Fwd URG Flags": fwd_urg_flags,
    "Bwd URG Flags": bwd_urg_flags,

    "Fwd Header Length": fwd_header_length,
    "Bwd Header Length": bwd_header_length,

    "Fwd Packets/s": fwd_packets_per_sec,
    "Bwd Packets/s": bwd_packets_per_sec,

    "Min Packet Length": min_packet_length,
    "Max Packet Length": max_packet_length,
    "Packet Length Mean": packet_length_mean,
    "Packet Length Std": packet_length_std,
    "Packet Length Variance": packet_length_variance,

    "FIN Flag Count": fin_flag_count,
    "SYN Flag Count": syn_flag_count,
    "RST Flag Count": rst_flag_count,
    "PSH Flag Count": psh_flag_count,
    "ACK Flag Count": ack_flag_count,
    "URG Flag Count": urg_flag_count,
    "CWE Flag Count": cwe_flag_count,
    "ECE Flag Count": ece_flag_count,

    "Down/Up Ratio": down_up_ratio,
    "Average Packet Size": average_packet_size,
    "Avg Fwd Segment Size": avg_fwd_segment_size,
    "Avg Bwd Segment Size": avg_bwd_segment_size,

    "Fwd Header Length.1": fwd_header_length,

    "Fwd Avg Bytes/Bulk": fwd_avg_bytes_bulk,
    "Fwd Avg Packets/Bulk": fwd_avg_packets_bulk,
    "Fwd Avg Bulk Rate": fwd_avg_bulk_rate,

    "Bwd Avg Bytes/Bulk": bwd_avg_bytes_bulk,
    "Bwd Avg Packets/Bulk": bwd_avg_packets_bulk,
    "Bwd Avg Bulk Rate": bwd_avg_bulk_rate,

    "Subflow Fwd Packets": subflow_fwd_packets,
    "Subflow Fwd Bytes": subflow_fwd_bytes,
    "Subflow Bwd Packets": subflow_bwd_packets,
    "Subflow Bwd Bytes": subflow_bwd_bytes,

    "Init_Win_bytes_forward": init_win_bytes_forward,
    "Init_Win_bytes_backward": init_win_bytes_backward,

    "act_data_pkt_fwd": act_data_pkt_fwd,
    "min_seg_size_forward": min_seg_size_forward,

    "Active Mean": active_mean,
    "Active Std": active_std,
    "Active Max": active_max,
    "Active Min": active_min,

    "Idle Mean": idle_mean,
    "Idle Std": idle_std,
    "Idle Max": idle_max,
    "Idle Min": idle_min
}


# Check that we actually created 78 features
print("Live features created:", len(live_features))


# Check for missing training features
missing_features = [
    feature for feature in training_features
    if feature not in live_features
]

extra_features = [
    feature for feature in live_features
    if feature not in training_features
]

print("\nMissing features:", missing_features)
print("Extra features:", extra_features)


# Arrange the live data in EXACTLY the same order as training
live_df = pd.DataFrame(
    [[live_features[feature] for feature in training_features]],
    columns=training_features
)

print("\nLive feature DataFrame shape:", live_df.shape)
print("\nMissing values:", live_df.isnull().sum().sum())

display(live_df)

Training features: 78

NameError: name 'fwd_iat_total' is not defined

In [49]:
# ============================================================
# STEP 25A — Build the remaining IAT feature variables
# ============================================================

import numpy as np
import time

# ------------------------------------------------------------
# Helper function: calculate inter-arrival times
# ------------------------------------------------------------

def calculate_iats(packets):
    if len(packets) < 2:
        return []

    timestamps = [
        float(packet.time)
        for packet in packets
        if hasattr(packet, "time")
    ]

    return [
        (timestamps[i] - timestamps[i - 1]) * 1_000_000
        for i in range(1, len(timestamps))
    ]


# Forward IAT
fwd_iats = calculate_iats(forward_packets)

if fwd_iats:
    fwd_iat_total = sum(fwd_iats)
    fwd_iat_mean = np.mean(fwd_iats)
    fwd_iat_std = np.std(fwd_iats) if len(fwd_iats) > 1 else 0
    fwd_iat_max = max(fwd_iats)
    fwd_iat_min = min(fwd_iats)
else:
    fwd_iat_total = 0
    fwd_iat_mean = 0
    fwd_iat_std = 0
    fwd_iat_max = 0
    fwd_iat_min = 0


# Backward IAT
bwd_iats = calculate_iats(backward_packets)

if bwd_iats:
    bwd_iat_total = sum(bwd_iats)
    bwd_iat_mean = np.mean(bwd_iats)
    bwd_iat_std = np.std(bwd_iats) if len(bwd_iats) > 1 else 0
    bwd_iat_max = max(bwd_iats)
    bwd_iat_min = min(bwd_iats)
else:
    bwd_iat_total = 0
    bwd_iat_mean = 0
    bwd_iat_std = 0
    bwd_iat_max = 0
    bwd_iat_min = 0


print("Forward IAT")
print("Total:", fwd_iat_total)
print("Mean:", fwd_iat_mean)
print("Std:", fwd_iat_std)
print("Max:", fwd_iat_max)
print("Min:", fwd_iat_min)

print("\nBackward IAT")
print("Total:", bwd_iat_total)
print("Mean:", bwd_iat_mean)
print("Std:", bwd_iat_std)
print("Max:", bwd_iat_max)
print("Min:", bwd_iat_min)

Forward IAT
Total: 1325.6072998046875
Mean: 1325.6072998046875
Std: 0
Max: 1325.6072998046875
Min: 1325.6072998046875

Backward IAT
Total: 0
Mean: 0
Std: 0
Max: 0
Min: 0

In [50]:
# STEP 26 — Check the 78 training features

import pandas as pd

X_train_sample = pd.read_csv(
    "../data/processed/X_train.csv",
    nrows=1
)

training_features = X_train_sample.columns.tolist()

print("Total training features:", len(training_features))

for i, feature in enumerate(training_features, start=1):
    print(f"{i:2}. {feature}")

Total training features: 78
 1. Destination Port
 2. Flow Duration
 3. Total Fwd Packets
 4. Total Backward Packets
 5. Total Length of Fwd Packets
 6. Total Length of Bwd Packets
 7. Fwd Packet Length Max
 8. Fwd Packet Length Min
 9. Fwd Packet Length Mean
10. Fwd Packet Length Std
11. Bwd Packet Length Max
12. Bwd Packet Length Min
13. Bwd Packet Length Mean
14. Bwd Packet Length Std
15. Flow Bytes/s
16. Flow Packets/s
17. Flow IAT Mean
18. Flow IAT Std
19. Flow IAT Max
20. Flow IAT Min
21. Fwd IAT Total
22. Fwd IAT Mean
23. Fwd IAT Std
24. Fwd IAT Max
25. Fwd IAT Min
26. Bwd IAT Total
27. Bwd IAT Mean
28. Bwd IAT Std
29. Bwd IAT Max
30. Bwd IAT Min
31. Fwd PSH Flags
32. Bwd PSH Flags
33. Fwd URG Flags
34. Bwd URG Flags
35. Fwd Header Length
36. Bwd Header Length
37. Fwd Packets/s
38. Bwd Packets/s
39. Min Packet Length
40. Max Packet Length
41. Packet Length Mean
42. Packet Length Std
43. Packet Length Variance
44. FIN Flag Count
45. SYN Flag Count
46. RST Flag Count
47. PSH Flag Count
48. ACK Flag Count
49. URG Flag Count
50. CWE Flag Count
51. ECE Flag Count
52. Down/Up Ratio
53. Average Packet Size
54. Avg Fwd Segment Size
55. Avg Bwd Segment Size
56. Fwd Header Length.1
57. Fwd Avg Bytes/Bulk
58. Fwd Avg Packets/Bulk
59. Fwd Avg Bulk Rate
60. Bwd Avg Bytes/Bulk
61. Bwd Avg Packets/Bulk
62. Bwd Avg Bulk Rate
63. Subflow Fwd Packets
64. Subflow Fwd Bytes
65. Subflow Bwd Packets
66. Subflow Bwd Bytes
67. Init_Win_bytes_forward
68. Init_Win_bytes_backward
69. act_data_pkt_fwd
70. min_seg_size_forward
71. Active Mean
72. Active Std
73. Active Max
74. Active Min
75. Idle Mean
76. Idle Std
77. Idle Max
78. Idle Min

In [85]:
# ============================================================
# STEP 27 — 78-FEATURE EXTRACTION FUNCTION
# ============================================================

import numpy as np
import pandas as pd
from scapy.all import IP, TCP


def calculate_iat_values(packets):
    """Calculate inter-arrival times in microseconds."""

    if len(packets) < 2:
        return []

    timestamps = [
        float(packet.time)
        for packet in packets
        if hasattr(packet, "time")
    ]

    return [
        (timestamps[i] - timestamps[i - 1]) * 1_000_000
        for i in range(1, len(timestamps))
    ]


def safe_mean(values):
    return float(np.mean(values)) if values else 0.0


def safe_std(values):
    return float(np.std(values)) if len(values) > 1 else 0.0


def safe_max(values):
    return float(max(values)) if values else 0.0


def safe_min(values):
    return float(min(values)) if values else 0.0


def extract_features(packets):

    # --------------------------------------------------------
    # Separate forward and backward packets
    # --------------------------------------------------------

    ip_tcp_packets = [
        p for p in packets
        if p.haslayer(IP) and p.haslayer(TCP)
    ]

    if not ip_tcp_packets:
        raise ValueError("No TCP/IP packets found.")

    first_packet = ip_tcp_packets[0]

    forward_ip = first_packet[IP].src
    forward_port = first_packet[TCP].sport

    forward_packets = [
        p for p in ip_tcp_packets
        if p[IP].src == forward_ip
        and p[TCP].sport == forward_port
    ]

    backward_packets = [
        p for p in ip_tcp_packets
        if not (
            p[IP].src == forward_ip
            and p[TCP].sport == forward_port
        )
    ]

    # --------------------------------------------------------
    # Packet lengths
    # --------------------------------------------------------

    all_lengths = [len(p) for p in ip_tcp_packets]

    fwd_lengths = [len(p) for p in forward_packets]
    bwd_lengths = [len(p) for p in backward_packets]

    # --------------------------------------------------------
    # Flow duration
    # --------------------------------------------------------

    timestamps = [
        float(p.time)
        for p in ip_tcp_packets
        if hasattr(p, "time")
    ]

    if len(timestamps) >= 2:
        flow_duration = (
            max(timestamps) - min(timestamps)
        ) * 1_000_000
    else:
        flow_duration = 0.0

    flow_duration_seconds = flow_duration / 1_000_000

    # --------------------------------------------------------
    # IAT
    # --------------------------------------------------------

    flow_iats = calculate_iat_values(ip_tcp_packets)
    fwd_iats = calculate_iat_values(forward_packets)
    bwd_iats = calculate_iat_values(backward_packets)

    # --------------------------------------------------------
    # Flow statistics
    # --------------------------------------------------------

    total_fwd_packets = len(forward_packets)
    total_bwd_packets = len(backward_packets)

    total_fwd_bytes = sum(fwd_lengths)
    total_bwd_bytes = sum(bwd_lengths)

    total_packets = len(ip_tcp_packets)
    total_bytes = sum(all_lengths)

    # --------------------------------------------------------
    # Rates
    # --------------------------------------------------------

    if flow_duration_seconds > 0:

        flow_bytes_per_sec = (
            total_bytes / flow_duration_seconds
        )

        flow_packets_per_sec = (
            total_packets / flow_duration_seconds
        )

        fwd_packets_per_sec = (
            total_fwd_packets / flow_duration_seconds
        )

        bwd_packets_per_sec = (
            total_bwd_packets / flow_duration_seconds
        )

    else:

        flow_bytes_per_sec = 0.0
        flow_packets_per_sec = 0.0
        fwd_packets_per_sec = 0.0
        bwd_packets_per_sec = 0.0

    # --------------------------------------------------------
    # TCP flags
    # --------------------------------------------------------

    fin_flag_count = sum(
        1 for p in ip_tcp_packets
        if p[TCP].flags & 0x01
    )

    syn_flag_count = sum(
        1 for p in ip_tcp_packets
        if p[TCP].flags & 0x02
    )

    rst_flag_count = sum(
        1 for p in ip_tcp_packets
        if p[TCP].flags & 0x04
    )

    psh_flag_count = sum(
        1 for p in ip_tcp_packets
        if p[TCP].flags & 0x08
    )

    ack_flag_count = sum(
        1 for p in ip_tcp_packets
        if p[TCP].flags & 0x10
    )

    urg_flag_count = sum(
        1 for p in ip_tcp_packets
        if p[TCP].flags & 0x20
    )

    ece_flag_count = sum(
        1 for p in ip_tcp_packets
        if p[TCP].flags & 0x40
    )

    cwe_flag_count = sum(
        1 for p in ip_tcp_packets
        if p[TCP].flags & 0x80
    )

    # --------------------------------------------------------
    # Header lengths
    # --------------------------------------------------------

    fwd_header_length = sum(
        (
            p[TCP].dataofs * 4
            if p[TCP].dataofs is not None
            else 20
        )
        for p in forward_packets
    )

    bwd_header_length = sum(
        (
            p[TCP].dataofs * 4
            if p[TCP].dataofs is not None
            else 20
        )
        for p in backward_packets
    )

    # --------------------------------------------------------
    # Packet statistics
    # --------------------------------------------------------

    min_packet_length = safe_min(all_lengths)
    max_packet_length = safe_max(all_lengths)
    packet_length_mean = safe_mean(all_lengths)
    packet_length_std = safe_std(all_lengths)

    packet_length_variance = (
        float(np.var(all_lengths))
        if all_lengths
        else 0.0
    )

    # --------------------------------------------------------
    # Forward packet statistics
    # --------------------------------------------------------

    fwd_packet_length_max = safe_max(fwd_lengths)
    fwd_packet_length_min = safe_min(fwd_lengths)
    fwd_packet_length_mean = safe_mean(fwd_lengths)
    fwd_packet_length_std = safe_std(fwd_lengths)

    # --------------------------------------------------------
    # Backward packet statistics
    # --------------------------------------------------------

    bwd_packet_length_max = safe_max(bwd_lengths)
    bwd_packet_length_min = safe_min(bwd_lengths)
    bwd_packet_length_mean = safe_mean(bwd_lengths)
    bwd_packet_length_std = safe_std(bwd_lengths)

    # --------------------------------------------------------
    # Flow IAT statistics
    # --------------------------------------------------------

    flow_iat_mean = safe_mean(flow_iats)
    flow_iat_std = safe_std(flow_iats)
    flow_iat_max = safe_max(flow_iats)
    flow_iat_min = safe_min(flow_iats)

    # --------------------------------------------------------
    # Forward IAT statistics
    # --------------------------------------------------------

    fwd_iat_total = sum(fwd_iats)
    fwd_iat_mean = safe_mean(fwd_iats)
    fwd_iat_std = safe_std(fwd_iats)
    fwd_iat_max = safe_max(fwd_iats)
    fwd_iat_min = safe_min(fwd_iats)

    # --------------------------------------------------------
    # Backward IAT statistics
    # --------------------------------------------------------

    bwd_iat_total = sum(bwd_iats)
    bwd_iat_mean = safe_mean(bwd_iats)
    bwd_iat_std = safe_std(bwd_iats)
    bwd_iat_max = safe_max(bwd_iats)
    bwd_iat_min = safe_min(bwd_iats)

    # --------------------------------------------------------
    # Create feature dictionary
    # --------------------------------------------------------

    features = {

        "Destination Port": first_packet[TCP].dport,

        "Flow Duration": flow_duration,

        "Total Fwd Packets": total_fwd_packets,
        "Total Backward Packets": total_bwd_packets,

        "Total Length of Fwd Packets": total_fwd_bytes,
        "Total Length of Bwd Packets": total_bwd_bytes,

        "Fwd Packet Length Max": fwd_packet_length_max,
        "Fwd Packet Length Min": fwd_packet_length_min,
        "Fwd Packet Length Mean": fwd_packet_length_mean,
        "Fwd Packet Length Std": fwd_packet_length_std,

        "Bwd Packet Length Max": bwd_packet_length_max,
        "Bwd Packet Length Min": bwd_packet_length_min,
        "Bwd Packet Length Mean": bwd_packet_length_mean,
        "Bwd Packet Length Std": bwd_packet_length_std,

        "Flow Bytes/s": flow_bytes_per_sec,
        "Flow Packets/s": flow_packets_per_sec,

        "Flow IAT Mean": flow_iat_mean,
        "Flow IAT Std": flow_iat_std,
        "Flow IAT Max": flow_iat_max,
        "Flow IAT Min": flow_iat_min,

        "Fwd IAT Total": fwd_iat_total,
        "Fwd IAT Mean": fwd_iat_mean,
        "Fwd IAT Std": fwd_iat_std,
        "Fwd IAT Max": fwd_iat_max,
        "Fwd IAT Min": fwd_iat_min,

        "Bwd IAT Total": bwd_iat_total,
        "Bwd IAT Mean": bwd_iat_mean,
        "Bwd IAT Std": bwd_iat_std,
        "Bwd IAT Max": bwd_iat_max,
        "Bwd IAT Min": bwd_iat_min,

        "Fwd PSH Flags": sum(
            1 for p in forward_packets
            if p[TCP].flags & 0x08
        ),

        "Bwd PSH Flags": sum(
            1 for p in backward_packets
            if p[TCP].flags & 0x08
        ),

        "Fwd URG Flags": sum(
            1 for p in forward_packets
            if p[TCP].flags & 0x20
        ),

        "Bwd URG Flags": sum(
            1 for p in backward_packets
            if p[TCP].flags & 0x20
        ),

        "Fwd Header Length": fwd_header_length,
        "Bwd Header Length": bwd_header_length,

        "Fwd Packets/s": fwd_packets_per_sec,
        "Bwd Packets/s": bwd_packets_per_sec,

        "Min Packet Length": min_packet_length,
        "Max Packet Length": max_packet_length,
        "Packet Length Mean": packet_length_mean,
        "Packet Length Std": packet_length_std,
        "Packet Length Variance": packet_length_variance,

        "FIN Flag Count": fin_flag_count,
        "SYN Flag Count": syn_flag_count,
        "RST Flag Count": rst_flag_count,
        "PSH Flag Count": psh_flag_count,
        "ACK Flag Count": ack_flag_count,
        "URG Flag Count": urg_flag_count,
        "CWE Flag Count": cwe_flag_count,
        "ECE Flag Count": ece_flag_count,

        "Down/Up Ratio": (
            total_bwd_packets / total_fwd_packets
            if total_fwd_packets > 0
            else 0
        ),

        "Average Packet Size": packet_length_mean,

        "Avg Fwd Segment Size": fwd_packet_length_mean,

        "Avg Bwd Segment Size": bwd_packet_length_mean,

        "Fwd Header Length.1": fwd_header_length,

        "Fwd Avg Bytes/Bulk": 0,
        "Fwd Avg Packets/Bulk": 0,
        "Fwd Avg Bulk Rate": 0,

        "Bwd Avg Bytes/Bulk": 0,
        "Bwd Avg Packets/Bulk": 0,
        "Bwd Avg Bulk Rate": 0,

        "Subflow Fwd Packets": total_fwd_packets,
        "Subflow Fwd Bytes": total_fwd_bytes,

        "Subflow Bwd Packets": total_bwd_packets,
        "Subflow Bwd Bytes": total_bwd_bytes,

        "Init_Win_bytes_forward": (
            int(forward_packets[0][TCP].window)
            if forward_packets
            else 0
        ),

        "Init_Win_bytes_backward": (
            int(backward_packets[0][TCP].window)
            if backward_packets
            else 0
        ),

        "act_data_pkt_fwd": sum(
            1
            for p in forward_packets
            if len(p[TCP].payload) > 0
        ),

        "min_seg_size_forward": (
            min(fwd_lengths)
            if fwd_lengths
            else 0
        ),

        "Active Mean": flow_iat_mean,
        "Active Std": flow_iat_std,
        "Active Max": flow_iat_max,
        "Active Min": flow_iat_min,

        "Idle Mean": 0,
        "Idle Std": 0,
        "Idle Max": 0,
        "Idle Min": 0,
    }

    return features

In [59]:
# STEP 28 — Create a test flow from the captured packets

from scapy.all import IP, TCP

# Use the packets from your existing capture
test_flow = packets

print("Packets in test flow:", len(test_flow))

for packet in test_flow:
    if packet.haslayer(IP) and packet.haslayer(TCP):
        print(packet.summary())

Packets in test flow: 3
IP / TCP 127.0.0.1:50000 > 127.0.0.1:8000 S
IP / TCP 127.0.0.1:8000 > 127.0.0.1:50000 SA
IP / TCP 127.0.0.1:50000 > 127.0.0.1:8000 PA / Raw

In [60]:
features = extract_features(test_flow)

print("Features extracted:", len(features))

Features extracted: 78

In [61]:
X_live = pd.DataFrame([features])

print("Shape:", X_live.shape)
print("Missing values:", X_live.isnull().sum().sum())

Shape: (1, 78)
Missing values: 0

In [63]:
# STEP 30 — Verify feature names and order

training_features = pd.read_csv(
    "../data/processed/X_train.csv",
    nrows=1
)

training_columns = list(training_features.columns)
live_columns = list(X_live.columns)

print("Training features:", len(training_columns))
print("Live features:", len(live_columns))

print("\nSame feature names:", set(training_columns) == set(live_columns))
print("Same feature order:", training_columns == live_columns)

Training features: 78
Live features: 78

Same feature names: True
Same feature order: True

In [64]:
# STEP 31 — Check the training feature scale

print(X_train.describe().loc[["mean", "std"]].T.to_string())

                                 mean  std
Destination Port            -0.454139  NaN
Flow Duration               -0.470183  NaN
Total Fwd Packets           -0.010413  NaN
Total Backward Packets      -0.009081  NaN
Total Length of Fwd Packets -0.083648  NaN
Total Length of Bwd Packets -0.007580  NaN
Fwd Packet Length Max       -0.262428  NaN
Fwd Packet Length Min        0.226321  NaN
Fwd Packet Length Mean      -0.156043  NaN
Fwd Packet Length Std       -0.260715  NaN
Bwd Packet Length Max       -0.430782  NaN
Bwd Packet Length Min        0.759052  NaN
Bwd Packet Length Mean      -0.385244  NaN
Bwd Packet Length Std       -0.427394  NaN
Flow Bytes/s                -0.052803  NaN
Flow Packets/s              -0.232582  NaN
Flow IAT Mean               -0.306199  NaN
Flow IAT Std                -0.385584  NaN
Flow IAT Max                -0.399878  NaN
Flow IAT Min                -0.056754  NaN
Fwd IAT Total               -0.462266  NaN
Fwd IAT Mean                -0.291428  NaN
Fwd IAT Std                 -0.361724  NaN
Fwd IAT Max                 -0.393717  NaN
Fwd IAT Min                 -0.125518  NaN
Bwd IAT Total               -0.367570  NaN
Bwd IAT Mean                -0.215801  NaN
Bwd IAT Std                 -0.251512  NaN
Bwd IAT Max                 -0.290570  NaN
Bwd IAT Min                 -0.123549  NaN
Fwd PSH Flags               -0.226002  NaN
Bwd PSH Flags                0.000000  NaN
Fwd URG Flags               -0.005807  NaN
Bwd URG Flags                0.000000  NaN
Fwd Header Length            0.001706  NaN
Bwd Header Length            0.001613  NaN
Fwd Packets/s               -0.211011  NaN
Bwd Packets/s               -0.169073  NaN
Min Packet Length            0.628682  NaN
Max Packet Length           -0.455675  NaN
Packet Length Mean          -0.414882  NaN
Packet Length Std           -0.446593  NaN
Packet Length Variance      -0.313486  NaN
FIN Flag Count              -0.182065  NaN
SYN Flag Count              -0.226002  NaN
RST Flag Count              -0.016637  NaN
PSH Flag Count              -0.651161  NaN
ACK Flag Count              -0.673035  NaN
URG Flag Count              -0.335870  NaN
CWE Flag Count              -0.005807  NaN
ECE Flag Count              -0.016681  NaN
Down/Up Ratio                0.429244  NaN
Average Packet Size         -0.402917  NaN
Avg Fwd Segment Size        -0.156043  NaN
Avg Bwd Segment Size        -0.385244  NaN
Fwd Header Length.1          0.001706  NaN
Fwd Avg Bytes/Bulk           0.000000  NaN
Fwd Avg Packets/Bulk         0.000000  NaN
Fwd Avg Bulk Rate            0.000000  NaN
Bwd Avg Bytes/Bulk           0.000000  NaN
Bwd Avg Packets/Bulk         0.000000  NaN
Bwd Avg Bulk Rate            0.000000  NaN
Subflow Fwd Packets         -0.010413  NaN
Subflow Fwd Bytes           -0.083648  NaN
Subflow Bwd Packets         -0.009081  NaN
Subflow Bwd Bytes           -0.007580  NaN
Init_Win_bytes_forward      -0.497989  NaN
Init_Win_bytes_backward     -0.249889  NaN
act_data_pkt_fwd            -0.007423  NaN
min_seg_size_forward         0.002575  NaN
Active Mean                 -0.135369  NaN
Active Std                  -0.110854  NaN
Active Max                  -0.159110  NaN
Active Min                  -0.109241  NaN
Idle Mean                   -0.375838  NaN
Idle Std                    -0.115877  NaN
Idle Max                    -0.381176  NaN
Idle Min                    -0.361859  NaN

In [66]:
# STEP 32 — Inspect scaled training data

X_train_sample = pd.read_csv(
    "../data/processed/X_train.csv",
    nrows=1000
)

print("Sample shape:", X_train_sample.shape)

print("\nMean of first 10 features:")
print(
    X_train_sample.iloc[:, :10]
    .mean()
    .to_string()
)

print("\nStd of first 10 features:")
print(
    X_train_sample.iloc[:, :10]
    .std()
    .to_string()
)

Sample shape: (1000, 78)

Mean of first 10 features:

Destination Port              -0.032302
Flow Duration                  0.001402
Total Fwd Packets             -0.002644
Total Backward Packets        -0.002813
Total Length of Fwd Packets   -0.001412
Total Length of Bwd Packets   -0.002870
Fwd Packet Length Max         -0.012762
Fwd Packet Length Min         -0.034760
Fwd Packet Length Mean        -0.035661
Fwd Packet Length Std         -0.013919

Std of first 10 features:
Destination Port               0.975432
Flow Duration                  1.003996
Total Fwd Packets              0.097319
Total Backward Packets         0.095353
Total Length of Fwd Packets    0.616287
Total Length of Bwd Packets    0.085233
Fwd Packet Length Max          0.829536
Fwd Packet Length Min          0.366165
Fwd Packet Length Mean         0.764769
Fwd Packet Length Std          0.812597

In [67]:
import os

print("Possible scaler files:\n")

for root, dirs, files in os.walk("../../"):
    for file in files:
        if "scal" in file.lower() or "standard" in file.lower():
            print(os.path.join(root, file))

Possible scaler files:

../../web-app-intrusion-detection\.venv\Lib\site-packages\fontTools\encodings\StandardEncoding.py
../../web-app-intrusion-detection\.venv\Lib\site-packages\fontTools\encodings\__pycache__\StandardEncoding.cpython-314.pyc
../../web-app-intrusion-detection\.venv\Lib\site-packages\fontTools\feaLib\variableScalar.py
../../web-app-intrusion-detection\.venv\Lib\site-packages\fontTools\feaLib\__pycache__\variableScalar.cpython-314.pyc
../../web-app-intrusion-detection\.venv\Lib\site-packages\fontTools\ttLib\scaleUpem.py
../../web-app-intrusion-detection\.venv\Lib\site-packages\fontTools\ttLib\standardGlyphOrder.py
../../web-app-intrusion-detection\.venv\Lib\site-packages\fontTools\ttLib\__pycache__\scaleUpem.cpython-314.pyc
../../web-app-intrusion-detection\.venv\Lib\site-packages\fontTools\ttLib\__pycache__\standardGlyphOrder.cpython-314.pyc
../../web-app-intrusion-detection\.venv\Lib\site-packages\jedi\third_party\typeshed\stdlib\lib2to3\fixes\fix_standarderror.pyi
../../web-app-intrusion-detection\.venv\Lib\site-packages\jedi\third_party\typeshed\stubs\ldap3\ldap3\protocol\formatters\standard.pyi
../../web-app-intrusion-detection\.venv\Lib\site-packages\jedi\third_party\typeshed\stubs\networkx\networkx\algorithms\flow\capacityscaling.pyi
../../web-app-intrusion-detection\.venv\Lib\site-packages\jedi\third_party\typeshed\stubs\seaborn\seaborn\_core\scales.pyi
../../web-app-intrusion-detection\.venv\Lib\site-packages\numpy\f2py\tests\src\string\scalar_string.f90
../../web-app-intrusion-detection\.venv\Lib\site-packages\numpy\typing\tests\data\fail\scalars.pyi
../../web-app-intrusion-detection\.venv\Lib\site-packages\numpy\typing\tests\data\pass\scalars.py
../../web-app-intrusion-detection\.venv\Lib\site-packages\numpy\typing\tests\data\pass\__pycache__\scalars.cpython-314.pyc
../../web-app-intrusion-detection\.venv\Lib\site-packages\numpy\typing\tests\data\reveal\scalars.pyi
../../web-app-intrusion-detection\.venv\Lib\site-packages\numpy\_core\_add_newdocs_scalars.py
../../web-app-intrusion-detection\.venv\Lib\site-packages\numpy\_core\_add_newdocs_scalars.pyi
../../web-app-intrusion-detection\.venv\Lib\site-packages\numpy\_core\include\numpy\arrayscalars.h
../../web-app-intrusion-detection\.venv\Lib\site-packages\numpy\_core\tests\test_scalarbuffer.py
../../web-app-intrusion-detection\.venv\Lib\site-packages\numpy\_core\tests\test_scalarinherit.py
../../web-app-intrusion-detection\.venv\Lib\site-packages\numpy\_core\tests\test_scalarmath.py
../../web-app-intrusion-detection\.venv\Lib\site-packages\numpy\_core\tests\test_scalarprint.py
../../web-app-intrusion-detection\.venv\Lib\site-packages\numpy\_core\tests\test_scalar_ctors.py
../../web-app-intrusion-detection\.venv\Lib\site-packages\numpy\_core\tests\test_scalar_methods.py
../../web-app-intrusion-detection\.venv\Lib\site-packages\numpy\_core\tests\__pycache__\test_scalarbuffer.cpython-314.pyc
../../web-app-intrusion-detection\.venv\Lib\site-packages\numpy\_core\tests\__pycache__\test_scalarinherit.cpython-314.pyc
../../web-app-intrusion-detection\.venv\Lib\site-packages\numpy\_core\tests\__pycache__\test_scalarmath.cpython-314.pyc
../../web-app-intrusion-detection\.venv\Lib\site-packages\numpy\_core\tests\__pycache__\test_scalarprint.cpython-314.pyc
../../web-app-intrusion-detection\.venv\Lib\site-packages\numpy\_core\tests\__pycache__\test_scalar_ctors.cpython-314.pyc
../../web-app-intrusion-detection\.venv\Lib\site-packages\numpy\_core\tests\__pycache__\test_scalar_methods.cpython-314.pyc
../../web-app-intrusion-detection\.venv\Lib\site-packages\numpy\_core\__pycache__\_add_newdocs_scalars.cpython-314.pyc
../../web-app-intrusion-detection\.venv\Lib\site-packages\numpy\_typing\_scalars.py
../../web-app-intrusion-detection\.venv\Lib\site-packages\numpy\_typing\__pycache__\_scalars.cpython-314.pyc
../../web-app-intrusion-detection\.venv\Lib\site-packages\pyarrow\scalar.pxi
../../web-app-intrusion-detection\.venv\Lib\site-packages\pyarrow\include\arrow\scalar.h
../../web-app-intrusion-detection\.venv\Lib\site-packages\pyarrow\include\arrow\visit_scalar_inline.h
../../web-app-intrusion-detection\.venv\Lib\site-packages\pyarrow\include\arrow\compute\api_scalar.h
../../web-app-intrusion-detection\.venv\Lib\site-packages\pyarrow\tests\test_scalars.py
../../web-app-intrusion-detection\.venv\Lib\site-packages\pyarrow\tests\__pycache__\test_scalars.cpython-314.pyc
../../web-app-intrusion-detection\.venv\Lib\site-packages\pygments\lexers\pascal.py
../../web-app-intrusion-detection\.venv\Lib\site-packages\pygments\lexers\__pycache__\pascal.cpython-314.pyc
../../web-app-intrusion-detection\.venv\Lib\site-packages\pygments\styles\friendly_grayscale.py
../../web-app-intrusion-detection\.venv\Lib\site-packages\pygments\styles\__pycache__\friendly_grayscale.cpython-314.pyc
../../web-app-intrusion-detection\.venv\Lib\site-packages\scipy\io\matlab\tests\data\testscalarcell_7.4_GLNX86.mat
../../web-app-intrusion-detection\.venv\Lib\site-packages\scipy\io\tests\data\scalar_byte.sav
../../web-app-intrusion-detection\.venv\Lib\site-packages\scipy\io\tests\data\scalar_byte_descr.sav
../../web-app-intrusion-detection\.venv\Lib\site-packages\scipy\io\tests\data\scalar_complex32.sav
../../web-app-intrusion-detection\.venv\Lib\site-packages\scipy\io\tests\data\scalar_complex64.sav
../../web-app-intrusion-detection\.venv\Lib\site-packages\scipy\io\tests\data\scalar_float32.sav
../../web-app-intrusion-detection\.venv\Lib\site-packages\scipy\io\tests\data\scalar_float64.sav
../../web-app-intrusion-detection\.venv\Lib\site-packages\scipy\io\tests\data\scalar_heap_pointer.sav
../../web-app-intrusion-detection\.venv\Lib\site-packages\scipy\io\tests\data\scalar_int16.sav
../../web-app-intrusion-detection\.venv\Lib\site-packages\scipy\io\tests\data\scalar_int32.sav
../../web-app-intrusion-detection\.venv\Lib\site-packages\scipy\io\tests\data\scalar_int64.sav
../../web-app-intrusion-detection\.venv\Lib\site-packages\scipy\io\tests\data\scalar_string.sav
../../web-app-intrusion-detection\.venv\Lib\site-packages\scipy\io\tests\data\scalar_uint16.sav
../../web-app-intrusion-detection\.venv\Lib\site-packages\scipy\io\tests\data\scalar_uint32.sav
../../web-app-intrusion-detection\.venv\Lib\site-packages\scipy\io\tests\data\scalar_uint64.sav
../../web-app-intrusion-detection\.venv\Lib\site-packages\scipy\io\tests\data\struct_scalars.sav
../../web-app-intrusion-detection\.venv\Lib\site-packages\scipy\io\tests\data\struct_scalars_replicated.sav
../../web-app-intrusion-detection\.venv\Lib\site-packages\scipy\io\tests\data\struct_scalars_replicated_3d.sav
../../web-app-intrusion-detection\.venv\Lib\site-packages\scipy\optimize\_root_scalar.py
../../web-app-intrusion-detection\.venv\Lib\site-packages\scipy\optimize\__pycache__\_root_scalar.cpython-314.pyc
../../web-app-intrusion-detection\.venv\Lib\site-packages\scipy\stats\tests\data\levy_stable\stable-loc-scale-sample-data.npy
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\numpy\f2py\tests\src\string\scalar_string.f90
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\numpy\typing\tests\data\fail\scalars.pyi
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\numpy\typing\tests\data\pass\scalars.py
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\numpy\typing\tests\data\pass\__pycache__\scalars.cpython-314.pyc
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\numpy\typing\tests\data\reveal\scalars.pyi
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\numpy\_core\_add_newdocs_scalars.py
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\numpy\_core\_add_newdocs_scalars.pyi
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\numpy\_core\include\numpy\arrayscalars.h
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\numpy\_core\tests\test_scalarbuffer.py
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\numpy\_core\tests\test_scalarinherit.py
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\numpy\_core\tests\test_scalarmath.py
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\numpy\_core\tests\test_scalarprint.py
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\numpy\_core\tests\test_scalar_ctors.py
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\numpy\_core\tests\test_scalar_methods.py
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\numpy\_core\tests\__pycache__\test_scalarbuffer.cpython-314.pyc
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\numpy\_core\tests\__pycache__\test_scalarinherit.cpython-314.pyc
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\numpy\_core\tests\__pycache__\test_scalarmath.cpython-314.pyc
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\numpy\_core\tests\__pycache__\test_scalarprint.cpython-314.pyc
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\numpy\_core\tests\__pycache__\test_scalar_ctors.cpython-314.pyc
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\numpy\_core\tests\__pycache__\test_scalar_methods.cpython-314.pyc
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\numpy\_core\__pycache__\_add_newdocs_scalars.cpython-314.pyc
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\numpy\_typing\_scalars.py
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\numpy\_typing\__pycache__\_scalars.cpython-314.pyc
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\pandas\tests\dtypes\cast\test_construct_from_scalar.py
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\pandas\tests\dtypes\cast\__pycache__\test_construct_from_scalar.cpython-314.pyc
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\pandas\tests\indexes\datetimes\test_scalar_compat.py
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\pandas\tests\indexes\datetimes\__pycache__\test_scalar_compat.cpython-314.pyc
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\pandas\tests\indexes\period\test_scalar_compat.py
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\pandas\tests\indexes\period\__pycache__\test_scalar_compat.cpython-314.pyc
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\pandas\tests\indexes\timedeltas\test_scalar_compat.py
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\pandas\tests\indexes\timedeltas\__pycache__\test_scalar_compat.cpython-314.pyc
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\pandas\tests\indexing\test_scalar.py
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\pandas\tests\indexing\__pycache__\test_scalar.cpython-314.pyc
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\pandas\tests\scalar\test_na_scalar.py
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\pandas\tests\scalar\__pycache__\test_na_scalar.cpython-314.pyc
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\pandas\tests\tseries\offsets\test_fiscal.py
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\pandas\tests\tseries\offsets\__pycache__\test_fiscal.cpython-314.pyc
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\scipy\io\matlab\tests\data\testscalarcell_7.4_GLNX86.mat
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\scipy\io\tests\data\scalar_byte.sav
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\scipy\io\tests\data\scalar_byte_descr.sav
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\scipy\io\tests\data\scalar_complex32.sav
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\scipy\io\tests\data\scalar_complex64.sav
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\scipy\io\tests\data\scalar_float32.sav
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\scipy\io\tests\data\scalar_float64.sav
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\scipy\io\tests\data\scalar_heap_pointer.sav
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\scipy\io\tests\data\scalar_int16.sav
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\scipy\io\tests\data\scalar_int32.sav
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\scipy\io\tests\data\scalar_int64.sav
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\scipy\io\tests\data\scalar_string.sav
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\scipy\io\tests\data\scalar_uint16.sav
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\scipy\io\tests\data\scalar_uint32.sav
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\scipy\io\tests\data\scalar_uint64.sav
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\scipy\io\tests\data\struct_scalars.sav
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\scipy\io\tests\data\struct_scalars_replicated.sav
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\scipy\io\tests\data\struct_scalars_replicated_3d.sav
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\scipy\optimize\_root_scalar.py
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\scipy\optimize\__pycache__\_root_scalar.cpython-314.pyc
../../web-app-intrusion-detection\app\backend\venv\Lib\site-packages\scipy\stats\tests\data\levy_stable\stable-loc-scale-sample-data.npy
../../web-app-intrusion-detection\app\frontend\node_modules\@reduxjs\toolkit\src\query\standardSchema.ts
../../web-app-intrusion-detection\app\frontend\node_modules\d3-scale\dist\d3-scale.js
../../web-app-intrusion-detection\app\frontend\node_modules\d3-scale\dist\d3-scale.min.js
../../web-app-intrusion-detection\app\frontend\node_modules\es-toolkit\dist\string\pascalCase.d.mts
../../web-app-intrusion-detection\app\frontend\node_modules\es-toolkit\dist\string\pascalCase.d.ts
../../web-app-intrusion-detection\app\frontend\node_modules\es-toolkit\dist\string\pascalCase.js
../../web-app-intrusion-detection\app\frontend\node_modules\es-toolkit\dist\string\pascalCase.mjs
../../web-app-intrusion-detection\app\frontend\node_modules\framer-motion\dist\es\value\use-inverted-scale.mjs
../../web-app-intrusion-detection\app\frontend\node_modules\framer-motion\dist\es\value\use-inverted-scale.mjs.map
../../web-app-intrusion-detection\app\frontend\node_modules\lucide-react\dist\esm\icons\image-upscale.mjs
../../web-app-intrusion-detection\app\frontend\node_modules\lucide-react\dist\esm\icons\image-upscale.mjs.map
../../web-app-intrusion-detection\app\frontend\node_modules\lucide-react\dist\esm\icons\scale-3-d.mjs
../../web-app-intrusion-detection\app\frontend\node_modules\lucide-react\dist\esm\icons\scale-3-d.mjs.map
../../web-app-intrusion-detection\app\frontend\node_modules\lucide-react\dist\esm\icons\scale-3d.mjs
../../web-app-intrusion-detection\app\frontend\node_modules\lucide-react\dist\esm\icons\scale-3d.mjs.map
../../web-app-intrusion-detection\app\frontend\node_modules\lucide-react\dist\esm\icons\scale.mjs
../../web-app-intrusion-detection\app\frontend\node_modules\lucide-react\dist\esm\icons\scale.mjs.map
../../web-app-intrusion-detection\app\frontend\node_modules\lucide-react\dist\esm\icons\scaling.mjs
../../web-app-intrusion-detection\app\frontend\node_modules\lucide-react\dist\esm\icons\scaling.mjs.map
../../web-app-intrusion-detection\app\frontend\node_modules\lucide-react\dist\esm\shared\src\utils\toPascalCase.mjs
../../web-app-intrusion-detection\app\frontend\node_modules\lucide-react\dist\esm\shared\src\utils\toPascalCase.mjs.map
../../web-app-intrusion-detection\app\frontend\node_modules\motion-dom\dist\es\projection\styles\scale-border-radius.mjs
../../web-app-intrusion-detection\app\frontend\node_modules\motion-dom\dist\es\projection\styles\scale-border-radius.mjs.map
../../web-app-intrusion-detection\app\frontend\node_modules\motion-dom\dist\es\projection\styles\scale-box-shadow.mjs
../../web-app-intrusion-detection\app\frontend\node_modules\motion-dom\dist\es\projection\styles\scale-box-shadow.mjs.map
../../web-app-intrusion-detection\app\frontend\node_modules\motion-dom\dist\es\projection\styles\scale-correction.mjs
../../web-app-intrusion-detection\app\frontend\node_modules\motion-dom\dist\es\projection\styles\scale-correction.mjs.map
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\es6\state\selectors\polarScaleSelectors.js
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\es6\state\selectors\combiners\combineConfiguredScale.js
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\es6\state\selectors\combiners\combineInverseScaleFunction.js
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\es6\state\selectors\combiners\combineRealScaleType.js
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\es6\util\ReduceCSSCalc.js
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\es6\util\useReportScale.js
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\es6\util\scale\CartesianScaleHelper.js
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\es6\util\scale\CustomScaleDefinition.js
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\es6\util\scale\RechartsScale.js
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\lib\state\selectors\polarScaleSelectors.js
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\lib\state\selectors\combiners\combineConfiguredScale.js
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\lib\state\selectors\combiners\combineInverseScaleFunction.js
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\lib\state\selectors\combiners\combineRealScaleType.js
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\lib\util\ReduceCSSCalc.js
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\lib\util\useReportScale.js
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\lib\util\scale\CartesianScaleHelper.js
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\lib\util\scale\CustomScaleDefinition.js
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\lib\util\scale\RechartsScale.js
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\types\state\selectors\polarScaleSelectors.d.ts
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\types\state\selectors\combiners\combineConfiguredScale.d.ts
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\types\state\selectors\combiners\combineInverseScaleFunction.d.ts
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\types\state\selectors\combiners\combineRealScaleType.d.ts
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\types\util\ReduceCSSCalc.d.ts
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\types\util\useReportScale.d.ts
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\types\util\scale\CartesianScaleHelper.d.ts
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\types\util\scale\CustomScaleDefinition.d.ts
../../web-app-intrusion-detection\app\frontend\node_modules\recharts\types\util\scale\RechartsScale.d.ts
../../web-app-intrusion-detection\app\frontend\node_modules\victory-vendor\d3-scale.d.ts
../../web-app-intrusion-detection\app\frontend\node_modules\victory-vendor\d3-scale.js
../../web-app-intrusion-detection\app\frontend\node_modules\victory-vendor\es\d3-scale.js

In [68]:
# STEP 34 — Find the original scaling code

import os

project_root = "../../"

for root, dirs, files in os.walk(project_root):

    # Ignore virtual environments
    dirs[:] = [
        d for d in dirs
        if d not in ["venv", ".venv", "__pycache__"]
    ]

    for file in files:

        if file.endswith((".py", ".ipynb")):

            path = os.path.join(root, file)

            try:
                with open(path, "r", encoding="utf-8") as f:
                    content = f.read()

                if (
                    "StandardScaler" in content
                    or "fit_transform" in content
                    or "X_train_scaled" in content
                ):
                    print("\nFOUND:")
                    print(path)

            except Exception:
                pass

FOUND:
../../web-app-intrusion-detection\notebooks\03_data_preprocessing.ipynb

FOUND:
../../web-app-intrusion-detection\notebooks\test.ipynb

In [69]:
# STEP 35 — Find the scaling code in the preprocessing notebook

import json

notebook_path = "../../web-app-intrusion-detection/notebooks/03_data_preprocessing.ipynb"

with open(notebook_path, "r", encoding="utf-8") as f:
    notebook = json.load(f)

for i, cell in enumerate(notebook["cells"]):
    source = "".join(cell.get("source", []))

    if (
        "StandardScaler" in source
        or "fit_transform" in source
        or "X_train_scaled" in source
        or "scaler" in source.lower()
    ):
        print("\n" + "=" * 70)
        print(f"CELL {i}")
        print("=" * 70)
        print(source)

======================================================================
CELL 7
======================================================================
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y_encoded = label_encoder.fit_transform(y)

======================================================================
CELL 13
======================================================================
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

======================================================================
CELL 14
======================================================================
print("X_train_scaled shape:", X_train_scaled.shape)
print("X_test_scaled shape:", X_test_scaled.shape)

======================================================================
CELL 15
======================================================================
print("Missing values in training data:",
      pd.isna(X_train_scaled).sum())

print("Missing values in testing data:",
      pd.isna(X_test_scaled).sum())

======================================================================
CELL 17
======================================================================
X_train_scaled_df = pd.DataFrame(
    X_train_scaled,
    columns=X.columns
)

X_test_scaled_df = pd.DataFrame(
    X_test_scaled,
    columns=X.columns
)

X_train_scaled_df.to_csv(
    processed_path / "X_train.csv",
    index=False
)

X_test_scaled_df.to_csv(
    processed_path / "X_test.csv",
    index=False
)

In [70]:
# STEP 36 — Show preprocessing cells before scaling

for i, cell in enumerate(notebook["cells"]):

    if 8 <= i <= 13:
        source = "".join(cell.get("source", []))

        print("\n" + "=" * 70)
        print(f"CELL {i}")
        print("=" * 70)
        print(source)

======================================================================
CELL 8
======================================================================
label_mapping = dict(
    zip(label_encoder.classes_,
        label_encoder.transform(label_encoder.classes_))
)

print(label_mapping)

======================================================================
CELL 9
======================================================================
print(X.dtypes.value_counts())

======================================================================
CELL 10
======================================================================
non_numeric_columns = X.select_dtypes(exclude=["number"]).columns

print("Non-numeric columns:")
print(non_numeric_columns)

======================================================================
CELL 11
======================================================================
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

======================================================================
CELL 12
======================================================================
print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)
print("Training labels:", y_train.shape)
print("Testing labels:", y_test.shape)

======================================================================
CELL 13
======================================================================
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [71]:
# STEP 37 — Show cells 11 and 12 completely

for i in [11, 12]:
    source = "".join(notebook["cells"][i].get("source", []))

    print("\n" + "=" * 70)
    print(f"CELL {i}")
    print("=" * 70)
    print(source)

======================================================================
CELL 11
======================================================================
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

======================================================================
CELL 12
======================================================================
print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)
print("Training labels:", y_train.shape)
print("Testing labels:", y_test.shape)

In [73]:
# STEP 38 — Recreate the original StandardScaler

from sklearn.preprocessing import StandardScaler
import pandas as pd

# Load the original cleaned dataset
cleaned_path = "../data/processed/cleaned_cicids2017.csv"

df = pd.read_csv(cleaned_path)

print("Dataset shape:", df.shape)

# Separate features and target
X_original = df.drop(columns=["Label"])
y_original = df["Label"]

print("Original X shape:", X_original.shape)
print("Original y shape:", y_original.shape)

Dataset shape: (2520798, 79)
Original X shape: (2520798, 78)
Original y shape: (2520798,)

In [74]:
# STEP 39 — Recreate the exact train/test split

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

label_encoder = LabelEncoder()

y_encoded_original = label_encoder.fit_transform(y_original)

X_train_original, X_test_original, y_train_original, y_test_original = train_test_split(
    X_original,
    y_encoded_original,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded_original
)

print("Training shape:", X_train_original.shape)
print("Testing shape:", X_test_original.shape)

Training shape: (2016638, 78)
Testing shape: (504160, 78)

In [75]:
# STEP 40 — Fit the original StandardScaler

scaler = StandardScaler()

scaler.fit(X_train_original)

print("Scaler fitted successfully.")
print("Number of features:", len(scaler.mean_))

Scaler fitted successfully.
Number of features: 78

In [76]:
# STEP 41 — Verify recreated scaler against X_train.csv

X_train_saved = pd.read_csv(
    "../data/processed/X_train.csv"
)

X_train_recreated = scaler.transform(X_train_original)

print("Saved shape:", X_train_saved.shape)
print("Recreated shape:", X_train_recreated.shape)

print(
    "First value saved:",
    X_train_saved.iloc[0, 0]
)

print(
    "First value recreated:",
    X_train_recreated[0, 0]
)

Saved shape: (2016638, 78)
Recreated shape: (2016638, 78)
First value saved: -0.4541388975882038
First value recreated: -0.4541388975882038

In [77]:
# STEP 42 — Scale the live traffic

X_live_scaled = scaler.transform(X_live)

print("Scaled live shape:", X_live_scaled.shape)
print("Missing values:", X_live_scaled.isnull().sum().sum() if hasattr(X_live_scaled, "isnull") else "0")

Scaled live shape: (1, 78)
Missing values: 0

In [78]:
# STEP 43 — Convert scaled live traffic back to DataFrame

X_live_scaled_df = pd.DataFrame(
    X_live_scaled,
    columns=training_columns
)

print("Shape:", X_live_scaled_df.shape)
print("Columns:", len(X_live_scaled_df.columns))

print("\nFirst 10 scaled features:")
print(X_live_scaled_df.iloc[0, :10])

Shape: (1, 78)
Columns: 78

First 10 scaled features:
Destination Port              -0.036032
Flow Duration                 -0.471027
Total Fwd Packets             -0.010413
Total Backward Packets        -0.009992
Total Length of Fwd Packets   -0.078993
Total Length of Bwd Packets   -0.007642
Fwd Packet Length Max         -0.231959
Fwd Packet Length Min          0.341269
Fwd Packet Length Mean        -0.079139
Fwd Packet Length Std         -0.233719
Name: 0, dtype: float64

In [79]:
# ============================================================
# STEP 44 — LOAD TRAINED RANDOM FOREST
# ============================================================

import joblib

model_path = "../models/random_forest.pkl"

model = joblib.load(model_path)

print("Model loaded successfully.")
print("Model type:", type(model))

Model loaded successfully.
Model type: <class 'sklearn.ensemble._forest.RandomForestClassifier'>

In [80]:
# ============================================================
# STEP 45 — PREDICT LIVE TRAFFIC
# ============================================================

prediction = model.predict(X_live_scaled_df)

print("Raw prediction:", prediction)
print("Predicted class:", int(prediction[0]))

Raw prediction: [0]
Predicted class: 0

In [81]:
# ============================================================
# STEP 46 — PREDICTION CONFIDENCE
# ============================================================

probabilities = model.predict_proba(X_live_scaled_df)

predicted_class = int(prediction[0])
confidence = float(probabilities[0][predicted_class]) * 100

print("Predicted class:", predicted_class)
print("Confidence:", round(confidence, 2), "%")

Predicted class: 0
Confidence: 96.0 %

In [83]:
# ============================================================
# STEP 47 — CONVERT CLASS TO ATTACK NAME
# ============================================================

label_mapping_path = "../data/processed/label_mapping.csv"

label_mapping_df = pd.read_csv(label_mapping_path)

print(label_mapping_df)

                Original_Label  Encoded_Label
0                       BENIGN              0
1                          Bot              1
2                         DDoS              2
3                DoS GoldenEye              3
4                     DoS Hulk              4
5             DoS Slowhttptest              5
6                DoS slowloris              6
7                  FTP-Patator              7
8                   Heartbleed              8
9                 Infiltration              9
10                    PortScan             10
11                 SSH-Patator             11
12    Web Attack � Brute Force             12
13  Web Attack � Sql Injection             13
14            Web Attack � XSS             14

In [84]:
# Find the attack name corresponding to the predicted encoded class

attack_row = label_mapping_df[
    label_mapping_df["Encoded_Label"] == predicted_class
]

attack_type = attack_row["Original_Label"].iloc[0]

print("Prediction:", attack_type)
print("Confidence:", round(confidence, 2), "%")

Prediction: BENIGN
Confidence: 96.0 %